name: Fallout
version: '${project.version}'
main: com.etsuni.fallout.Fallout
api-version: 1.16
commands:
  fallout:
    description: Fallout base command
    permission: fallout.*
    permission-message: "You don't have permissions to use this command."
permissions:
  fallout.*:
    description: Allows a player to use all fallout commands.